version: '2'
services:
  nginx:
    image: millerhooks/eh-nginx:0.1
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - chat
    volumes:
      - ./compose/nginx/conf.d:/etc/nginx/conf.d
    labels:
      linked_to: "chat"

  chat:
    build: ./compose/react-chat
    image: chat
    container_name: chat
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "3000"
    labels:
      linked_to: "mongo"

  mongo:
    image: mongo
    container_name: mongo
