version: '2'
services:
  nginx:
    image: millerhooks/eh-nginx:0.1
    ports:
      - "80:80"
      - "443:443"
    links:
      - chat
    volumes:
      - ./compose/nginx/conf.d:/etc/nginx/conf.d

  chat:
    build: ./compose/react-chat
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "3000"

  mongo:
    image: mongo